spring.application.name=annotations-demo
#server.port=8082
#app.welcome.message=Hello Spring Devs
#app.db.url=jdbc:mysql//localhost:3306/db
#app.user.name=esha
#app.user.email=contact@thinkconstructive.com
#app.cloud.provider.name=Google
