spring.application.name=annotations-demo
db.connection.url=jdbc:postgresql://localhost:5432/myapp
db.connection.username=root
db.connection.password=pass1
db.connection.pool-size=30
#spring.profiles.active=dev
logging.level.org.springframework=DEBUG